# Generated by Django 4.2.1 on 2024-06-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid_app', '0015_alter_auctionuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionuser',
            name='membership',
        ),
    ]
